version: '3.8'

services:
  isle-server:
    build:
      context: ./src
      dockerfile: server/Dockerfile
    environment:
      - PORT=56556
      - PYTHONUNBUFFERED=1
    ports:
      - "56556:56556"
    restart: unless-stopped
